name: MY‑NIX

on:
  push:
    branches: ['*']

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: amd64
            platform: linux/amd64
            target: x86

          - runner: ubuntu-24.04-arm
            arch: arm64
            platform: linux/arm64
            target: pi

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (${{ matrix.arch }})
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: ptrsr/my-nix:${{ matrix.arch }}
          load: true           # load into local Docker daemon

      - name: Create dist folder
        run: mkdir -p "$GITHUB_WORKSPACE/dist"

      - name: Build NixOS image in container
        run: |
          docker run --rm \
            -e TARGET=${{ matrix.target }} \
            -v "$GITHUB_WORKSPACE/dist:/dist" \
            -v "$GITHUB_WORKSPACE/src:/src" \
            ptrsr/my-nix:${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: distro-${{ matrix.target }}
          path: dist/distro-${{ matrix.target }}.img.zst
